name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test_api:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          echo Instalação das depedências do Projeto
          pip install robotframework
          pip install robotframework-requests

      - name: Run Robot Framework tests
        env:
          PYTHONWARNINGS: "ignore:Unverified HTTPS request"
        run: |
          echo Executando os testes de API do Robot
          robot --name "API and Web Tests" --outputdir results/ web/tests || true
    
      - name: Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report-api
          path: results/

  merge:
    name: Merge Reports
    runs-on: ubuntu-latest
    needs: 
      - test_api

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          echo Instalação das depedências do Projeto
          pip install robotframework

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with: 
          path: results/

      - name: Merge Reports
        run: |
          rebot --merge results/robot-framework-report-api/output.xml
          ls -a

      - name: Upload Merge Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report
          path: ./*.html

  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    needs: 
      - merge
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://marilliadantas.github.io/thementalist-academy-front-robot/report.html
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: robot-framework-report

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4